- hosts: all
  tasks:
  - name: install the packages
    yum:
      name: 
        - httpd
        - wget
        - tree
        - vim
      state: latest
  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started
  - name: Enable service httpd, and not touch the state
    service:
      name: httpd
      enabled: yes

  - name: stop httpd
    service:
      name: httpd
      state: stopped
  
  # - name: remove the Apache package
  #   yum:
  #     name: httpd
  #     state: absent